os: Visual Studio 2015

environment:
  matrix:
    - CLI_VERSION: Latest

matrix:
  allow_failures:
    - CLI_VERSION: Latest

install:
  - ps: .\scripts\show-dotnet-info.ps1
  # Download install script to install .NET cli in .dotnet dir
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\obtain\install.ps1 -Channel "preview" -version "$env:CLI_VERSION" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  # dotnet info
  - ps: dotnet restore
  - ps: dotnet pack src\Bezysoftware.Navigation.Interfaces
  - ps: dotnet pack src\Bezysoftware.Navigation.UWP

test: off 
version: 0.0.1.{build}

artifacts:
- path: src\**\*.nupkg